alert("JavaScript был изобретен американским программистом и хакером Бренданом Эйхом, работавшим в Netscape Communications.. ")
alert("..за 10 дней..")
alert("..в 1995 году.")
alert("JavaScript - это не Java!")
alert("Спецификация (формальное описание синтаксиса, базовых объектов и алгоритмов) языка JavaScript называется ECMAScript.")
